###############################################################################
#+---------------------------------------------------------------------------+#
#|                      AdvancedFishing Plugin Config                        |#
#|                         Programmed by 34yannik                            |#
#|                       https://github.com/34yannik                         |#
#+---------------------------------------------------------------------------+#
###############################################################################

##################################
#                                #
#         Plugin Settings        #
#                                #
##################################

